# -*- coding: utf-8 -*-
"""Pose Estimation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rO6SFRtQ5czKuu-oF29uEJz8B0eNxoIT
"""

import cv2
import mediapipe as mp
import numpy as np
import time

#Mediapipe Setup
mp_draw = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose
pose = mp_pose.Pose(
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
)

#Video Setup
cap = cv2.VideoCapture('/content/SampleSideonSideBatting.mov')

#variable
cap = cv2.VideoCapture('/content/SampleSideonSideBatting.mov')

#Angle Function
def calculate_angle(a, b, c):
    a = np.array(a)  # shoulder
    b = np.array(b)  # elbow
    c = np.array(c)  # wrist

    ba = a - b
    bc = c - b

    cosine_angle = np.dot(ba, bc) / (np.linalg.norm(ba) * np.linalg.norm(bc))
    angle = np.degrees(np.arccos(cosine_angle))
    return angle

#Main loop
while True:
    success, img = cap.read()
    if not success:
        break

    imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    results = pose.process(imgRGB)

    if results.pose_landmarks:
        mp_draw.draw_landmarks(
            img,
            results.pose_landmarks,
            mp_pose.POSE_CONNECTIONS
        )

        landmarks = results.pose_landmarks.landmark
        h, w, _ = img.shape

#Right arm keypoints
shoulder = [landmarks[12].x * w, landmarks[12].y * h]
        elbow    = [landmarks[14].x * w, landmarks[14].y * h]
        wrist    = [landmarks[16].x * w, landmarks[16].y * h]

# Metric 1: Elbow Angle
        elbow_angle = calculate_angle(shoulder, elbow, wrist)

# Metric : wrist velocity
wrist_speed = 0
        if prev_wrist is not None:
            wrist_speed = np.linalg.norm(
                np.array(wrist) - np.array(prev_wrist)
            )
            wrist_speed_history.append(wrist_speed)

# Swing Phases
if wrist_speed < 10 and wrist[0] < elbow[0]:
                cv2.putText(
                    img, "BACKSWING",
                    (50, 140),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1, (0, 255, 255), 2
                )

            if wrist_speed > 25:
                cv2.putText(
                    img, "BAT SWING (DOWNSWING)",
                    (50, 180),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1, (0, 255, 0), 2
                )

        prev_wrist = wrist

# Metric 3: Swing Stability
if len(wrist_speed_history) > 15:
            stability = np.std(wrist_speed_history[-15:])
            if stability > 6:
                cv2.putText(
                    img, "UNSTABLE SWING",
                    (50, 220),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    0.9, (0, 0, 255), 2
                )

# Display Metric
cv2.putText(
            img, f"Elbow Angle: {int(elbow_angle)} deg",
            (50, 80),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8, (255, 255, 0), 2
        )

        cv2.putText(
            img, f"Wrist Speed: {int(wrist_speed)}",
            (50, 110),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8, (255, 200, 0), 2
        )

# FPS
cTime = time.time()
    fps = 1 / (cTime - pTime) if cTime != pTime else 0
    pTime = cTime

    cv2.putText(
        img, f"FPS: {int(fps)}",
        (20, 40),
        cv2.FONT_HERSHEY_PLAIN,
        2, (255, 0, 0), 2
    )

    cv2.imshow("Right-Hand Bat Swing Analysis", img)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break


cap.release()
cv2.destroyAllWindows()