"""
RSA-based digital signatures for tamper-proofing alerts.

Every anomaly alert generated by the SystemSentinelAgent is signed with the
IDS's private key before it is emailed or logged. Administrators (or any
downstream consumer) can verify authenticity/integrity with the matching
public key, so a spoofed or altered alert is immediately detectable.
"""

import base64
import os

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding, rsa

from config import config


def generate_key_pair(key_size: int = 2048) -> None:
    """Generate an RSA key pair and write it to the configured paths."""
    os.makedirs(os.path.dirname(config.RSA_PRIVATE_KEY_PATH), exist_ok=True)

    private_key = rsa.generate_private_key(public_exponent=65537, key_size=key_size)
    public_key = private_key.public_key()

    with open(config.RSA_PRIVATE_KEY_PATH, "wb") as f:
        f.write(
            private_key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.PKCS8,
                encryption_algorithm=serialization.NoEncryption(),
            )
        )

    with open(config.RSA_PUBLIC_KEY_PATH, "wb") as f:
        f.write(
            public_key.public_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PublicFormat.SubjectPublicKeyInfo,
            )
        )


def _load_private_key():
    with open(config.RSA_PRIVATE_KEY_PATH, "rb") as f:
        return serialization.load_pem_private_key(f.read(), password=None)


def _load_public_key():
    with open(config.RSA_PUBLIC_KEY_PATH, "rb") as f:
        return serialization.load_pem_public_key(f.read())


def sign_message(message: str) -> str:
    """Sign a UTF-8 message and return the signature as a base64 string."""
    private_key = _load_private_key()
    signature = private_key.sign(
        message.encode("utf-8"),
        padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=padding.PSS.MAX_LENGTH),
        hashes.SHA256(),
    )
    return base64.b64encode(signature).decode("utf-8")


def verify_signature(message: str, signature_b64: str) -> bool:
    """Verify a base64-encoded signature against the original message."""
    public_key = _load_public_key()
    signature = base64.b64decode(signature_b64)
    try:
        public_key.verify(
            signature,
            message.encode("utf-8"),
            padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=padding.PSS.MAX_LENGTH),
            hashes.SHA256(),
        )
        return True
    except Exception:
        return False


if __name__ == "__main__":
    generate_key_pair()
    print(f"RSA key pair written to {config.RSA_PRIVATE_KEY_PATH} and {config.RSA_PUBLIC_KEY_PATH}")
